### ISSUE TITLE
Windows 7 + Animate CC 2015/2017 installation problem

### ISSUE THREAD

**Issue by kulabros** [jiborobot/pixi-animate-extension#32]
Hi all there,

I've allready successfully installed pixi-animate add-on, to Animate CC on my Mac. Add-on was installed via Creative Cloud app, and in Animate is now new PixiAnimate project type with custom publish settings, tested, works great, very nice.

There are several problems with Windows 7 x64 SP1 installation in my case. Node.js, NPM installed, up-to-date, electron-prebuilt installed ok, Visual Studio Community installed, add-on on Adobe's site acquired, installed, synced turned on in cc and animate, regedit changes, pixi-animate installed,..  

1) First problem is when trying to build and install plugin (gulp --plugin --install) > ending with 'no gulpfile found'.

2) Can't find add-on - never shows in Adobe CC app to be installed, and zxt extension installation can't be done, since I'm on Animate CC 2017, and Extension Manager CC can't install this type of extensions now. So, I see on my mac's CC journal, that PIXIAnimate add-on was installed, and I expected the same on Windows, but I've tried all the steps, many times, and never got the add-on into Animate CC.

Thanks for any help, good luck with pixi-animate! :)

**Comment by kulabros** [comment]
Well, I reverted to Animate CC 2015, installed extension via extension manager, na now, almost everything works. PixiAnimate custom project and settings is in Animate. But, when I want to publish, it says: ERROR: Electronis required to be installed in youtr global NPM package repository. Install by running the following from commandline: npm install electron-prebuilt -g.  Of course, I followed installation steps and installed elecron, via npm. As the error message says, it can't see/find my electron installation on windows. Is it possible to fix this with some linkage, or specific installation directory? Thanks a lot

**Comment by kulabros** [comment]
One thing I didn't mention. I wasn't able to do last line of windows installation instructions - install and build plugin (gulp --plugin --install) .. Command line is giving me error: no gulpfile found. I haven't found solution for this yet. Sudenly, I have PixiAnimate extension both in CC 2015 and CC 2017, but I can't export (publish, because of electron error I mention before.

**Comment by bigtimebuddy** [comment]
Hi @kulabros, thanks for digging in here and provide lots of info.

Sounds like there are two issues: unable to build from source (gulpfile not found) and Electron not found when trying to publish from Animate. Is this correct?

Originally, I had developed the extension on MacOS and then on Windows 10. Maybe there probably are some subtle pathing differences between NPM global modules in Windows 7 and Windows 10 which are causing it to not find Electron? [Here](https://github.com/jiborobot/pixi-animate-extension/blob/master/src/PixiAnimate/src/Utils.cpp#L1045-L1048) is the place in the code where it launches Electron on Windows. Could you try to launch `electron` from the PowerShell on Windows and see if it opens?

Good news is that I'm getting a Windows 7 machine next week so that I can help verify more. If you are just trying to get the extension up and running, grab the [latest release](https://github.com/jiborobot/pixi-animate-extension/releases) and install using [Manage Extension utility](https://blogs.adobe.com/creativecloud/installing-zxp-extensions-using-the-manage-extensions-utility/).

Unable to find the gulpfile when building seems like another issue entirely and might be useful to track that as a separate issue here.

**Comment by kulabros** [comment]
Hi @bigtimebuddy, thank you for this info. Yeah, these are two issues. Let this thread to be for Electron not found when trying to publish from Animace CC.

Well, it seems electron is starting OK from PowerShell. Electron says it is version 1.4.13 and to run app with electron, execute the following command in your console or teminal: "C:\Users\User_XXX\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\electron.exe path-to-your-app" .. So maybe, that's the right path.

Yeah, I have to fix my Mac's Animate CC installation, caused it's somehow failed and I'm not able to remove it, fix it, reinstall, or update, there are some issues with Creative Cloud, so I was wondering to run Windows version, until I fix my Mac installation.
